export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS'

export const COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS'
export const DELETE_ALL_TODOS = 'DELETE_ALL_TODOS'

export const UPDATE_TODO_STATUS_FILTER = 'UPDATE_TODO_STATUS_FILTER'
export const UPDATE_TODO_DATE_FILTER = 'UPDATE_TODO_DATE_FILTER'
